version: 0.0
os: linux
files:
  - source: src/app.js
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
    - location: scripts/install-deps.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop-app.sh
      timeout: 300
      runas: root