version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: scripts/install-deps.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
  - location: scripts/after-install.sh
    timeout: 300
    runas: ubuntu
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop-app.sh
      timeout: 300
      runas: ubuntu