# aws codebuild for React and deployment to S3
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm ci
      - mkdir dist
      - cp -R src node_modules dist/
  post_build:
    commands:
      - echo Build completed on `date`
  artifacts:
    files:
      - '**/*'
    base-directory: 'dist'