# aws codebuild for React and deployment to S3
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - apt-get install python3-setuptools build-essential -y
      - pip -V
      - export PATH=$PATH:/root/.local/bin
      - pip install --upgrade --user awsebcli
      - eb --version
      - echo Installing source NPM dependencies...
      - npm ci
      - eb deploy develop
  build:
    commands:
      - echo build started on `date`
  post_build:
    commands:
      - echo build completed on `date`